### ISSUE TITLE
AttributeError: 'module' object has no attribute 'isgenerator'

### ISSUE THREAD

**Issue by moshen** [enaeseth/swirl#1]
I'm not sure if I'm missing something.  I'm new to Tornado and thought your enhancements looked interesting.  I made a test similar to your example and I can't seem to get it to work.

```
$ python swirlTest.py 
ERROR:root:Uncaught exception GET /goo (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8888', method='GET', uri='/goo', version='HTTP/1.1', remote_ip='127.0.0.1', remote_ip='127.0.0.1', body='', headers={'Host': 'localhost:8888', 'Accept-Language': 'en-us,en;q=0.5', 'Accept-Encoding': 'gzip,deflate', 'Keep-Alive': '300', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1.8) Gecko/20100202 Firefox/3.5.8', 'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "/Library/Python/2.5/site-packages/tornado/web.py", line 688, in _execute
    getattr(self, self.request.method.lower())(*args, **kwargs)
  File "build/bdist.macosx-10.5-i386/egg/swirl.py", line 40, in run_async_routine
    if not inspect.isgenerator(gen):
AttributeError: 'module' object has no attribute 'isgenerator'
ERROR:root:500 GET /goo (127.0.0.1) 3.96ms
```

swirlTest.py:
    import tornado.httpserver
    import tornado.ioloop
    import tornado.web
    import tornado.httpclient
    import swirl

```
class GooHandler(tornado.web.RequestHandler):
    @swirl.asynchronous
    def get(self):
        http = http = tornado.httpclient.AsyncHTTPClient()
        url = 'http://www.google.com'

        try:
            response = yield lambda cb: http.fetch(url, cb)
        except tornado.httpclient.HTTPError:
            raise tornado.web.HTTPError(500, 'fetch failed')

        self.write(response.body)

application = tornado.web.Application([
    (r"/goo", GooHandler),
])

if __name__ == "__main__":
    http_server = tornado.httpserver.HTTPServer(application)
    http_server.listen(8888)
    tornado.ioloop.IOLoop.instance().start()
```

**Comment by enaeseth** [comment]
Hi (and sorry for the delay in responding),

Swirl was using Python's `isgenerator` function, which only appeared in 2.6. Compatibility with 2.5 has now been restored in d1ac84d6ba67665a02d06efef1505a34d203a5ff.

**Comment by moshen** [comment]
Thanks!
